# Generated by Django 3.2.4 on 2021-08-06 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20210806_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=400)),
                ('details', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='product_image/')),
                ('brannd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.brand')),
            ],
        ),
    ]
