# Generated by Django 3.2.4 on 2021-08-06 19:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brannd',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='application.category'),
            preserve_default=False,
        ),
    ]
