# Generated by Django 3.2.4 on 2021-08-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20210806_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
