# Generated by Django 3.2.4 on 2021-08-09 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0008_rename_name_product_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('type', models.IntegerField()),
                ('isFlaggedFraud', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=5, default='', max_digits=50)),
                ('oldbalanceOrg', models.DecimalField(decimal_places=5, default='', max_digits=50)),
                ('newbalanceOrig', models.DecimalField(decimal_places=5, default='', max_digits=50)),
                ('oldbalanceDest', models.DecimalField(decimal_places=5, default='', max_digits=50)),
                ('newbalanceDest', models.DecimalField(decimal_places=5, default='', max_digits=50)),
                ('errorBalanceOrig', models.DecimalField(decimal_places=5, default='', max_digits=50)),
                ('errorBalanceDest', models.DecimalField(decimal_places=5, default='', max_digits=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
